# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14dce79babb73a1ff077c7ca66535a33b19e6567a7a9ca9befafa32298e3cf937e81571d644622ce5269fcd1a20e0c057aaa973a3f3fa65ba6484f3194f1c5b6

test:
  secret_key_base: dac59476ffb4a25fd84cc04a94a7b79cae8aeeffe855e6026405f5920da55142ed7c78f48f20f921b1472ec01ec1a63faf506b7eb7a804143f742352ec4865d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
